//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INT.Service.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInOut
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string TipoMovimiento { get; set; }
        public string IdSensor { get; set; }
        public string StsModificacion { get; set; }
    }
}
