//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INT.Service.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKINOUT
    {
        public string Userid { get; set; }
        public System.DateTime CheckTime { get; set; }
        public string CheckType { get; set; }
        public string Sensorid { get; set; }
        public string StsModificacion { get; set; }
    }
}
