//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INT.Service.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentDevice
    {
        public string FromIpAddress { get; set; }
        public string ToDataBase { get; set; }
        public int SyncId { get; set; }
        public string DeviceName { get; set; }
        public string CommunicationType { get; set; }
        public string DeviceType { get; set; }
        public string SensorName { get; set; }
    }
}
