//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INT.Service.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduler
    {
        public string JobName { get; set; }
        public string TriggerName { get; set; }
        public string ScheduleGroup { get; set; }
        public string Second { get; set; }
        public string Minute { get; set; }
        public string Hour { get; set; }
        public string Day { get; set; }
    }
}
